spring:

  # DB
  profiles:
    include: mysql,jwt,aws

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        # batch
#        generate_statistics: true
#        jdbc:
#          batch_size: 50
#        order_inserts: true 
    # DB    
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # data  
  data:
    jpa:
      repositories:
        enabled: true
  # jackson  
  jackson:
    serialization:
      fail-on-empty-beans: false



    default-property-inclusion: non-null  

     
logging:
  level:
    com.balloon: debug    